#!/bin/sh
set -eu

if [ -z "${DASHBOARD_AUTH_USER:-}" ]; then
  echo "DASHBOARD_AUTH_USER is required" >&2
  exit 1
fi

if [ -z "${DASHBOARD_AUTH_PASSWORD_BCRYPT_HASH:-}" ]; then
  echo "DASHBOARD_AUTH_PASSWORD_BCRYPT_HASH is required" >&2
  exit 1
fi

if [ -z "${DASHBOARD_AUTH_SESSION_SECRET:-}" ]; then
  echo "DASHBOARD_AUTH_SESSION_SECRET is required" >&2
  exit 1
fi

case "$DASHBOARD_AUTH_USER" in
  *[!A-Za-z0-9_.@-]*)
    echo "DASHBOARD_AUTH_USER may contain only letters, digits, '_', '.', '@', and '-'" >&2
    exit 1
    ;;
esac

if ! printf '%s' "$DASHBOARD_AUTH_PASSWORD_BCRYPT_HASH" | grep -Eq '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$'; then
  echo "DASHBOARD_AUTH_PASSWORD_BCRYPT_HASH must be a bcrypt hash generated by: npm run auth:hash -- 'plain-password-here'" >&2
  exit 1
fi

if [ "${#DASHBOARD_AUTH_SESSION_SECRET}" -lt 32 ]; then
  echo "DASHBOARD_AUTH_SESSION_SECRET must be at least 32 characters" >&2
  exit 1
fi

node /app/scripts/auth-service.mjs &
